apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-operator-sa
  namespace: homework
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-operator-role
rules:
  - apiGroups: ["otus.homework"]  
    resources: ["mysqls"]         
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]

  - apiGroups: [""]                  
    resources: ["persistentvolumes", "persistentvolumeclaims", "services", "events"]         
    verbs: ["get", "list", "create", "delete", "patch", "update"]

  - apiGroups: ["apps"]              
    resources: ["deployments", "deployments/status"]
    verbs: ["get", "list", "create", "delete", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-operator-binding
subjects:
  - kind: ServiceAccount
    name: my-operator-sa
    namespace: homework
roleRef:
  kind: ClusterRole
  name: my-operator-role
  apiGroup: rbac.authorization.k8s.io