apiVersion: v1
kind: Pod
metadata:
  name: nginx-distroless
  namespace: homework
spec:
  containers:
    - name: nginx
      image: kyos0109/nginx-distroless:latest
      ports:
        - containerPort: 80