apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: homework
  name: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: cherstvyy/nginx-with-status:17.06.2025
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: homework
  name: nginx-app
spec:
  selector:
    app: nginx-app
  ports:
    - port: 8080
      targetPort: 8080
      name: http